name: Build on multiple platforms

on:
  workflow_dispatch

jobs:
  build_macos:
    runs-on: macos-12
    
    steps:    
    - uses: actions/checkout@v3
    
    - name: Build
      shell: bash
      run:  |
              ./build_deps
              ./build_redist
  build_ubuntu:
    runs-on: ubuntu-20.04
    
    steps:    
    - uses: actions/checkout@v3   
    
    - name:  Restore cached build 
      uses: actions/cache/restore@v3
      id: restore_cache
      with:
        path: ${{github.workspace}}/
        key: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }} 
    
    - name: Update git submodules
      run:  git submodule update --init --recursive   
    
    - name:  Install Ubuntu  Packages
      shell: bash
      run: ./install-ubuntu-packages
  
    - name: Build
      shell: bash
      run:  |
              ./build_deps
              ./build_redist
  finish:
    needs:
      - build_ubuntu
      - build_macos
    runs-on: ubuntu-20.04
    steps:
    
    - name:  Save build cache
      uses: actions/cache/save@v3
      id: save_cache
      with:
        path: ${{github.workspace}}/
        key:  ${{ steps.restore_cache.outputs.cache-primary-key }}

    - uses: actions/upload-artifact@v3
      with:
        name: libacfutils
        path: ./
