name: Build on multiple platforms

on:
  workflow_dispatch

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04
    
    steps:    
    - uses: actions/checkout@v3   
    
    - name:  Restore cached build 
      uses: actions/cache@v3
      with:
        path: ./*
        key: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }}-${{ github.run_id }} 
        restore-keys: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }}
        enableCrossOsArchive: true
    
    - name: Update git submodules
      run:  git submodule update --init --recursive   
    
    - name:  Install Ubuntu  Packages
      shell: bash
      run: ./install-ubuntu-packages
  
    - name: Build
      shell: bash
      run:  |
              ./build_deps
              ./build_redist
        
  build_macos:
    needs:
      - build_ubuntu
    runs-on: macos-12
    
    steps:    
    - uses: actions/checkout@v3 
    
    - name:  Restore cached build 
      uses: actions/cache@v3
      with:
        path: ./*
        key: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }}-${{ github.run_id }} 
        restore-keys: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }}
        enableCrossOsArchive: true  

    - name: Build
      shell: bash
      run:  |
              ./build_deps
              ./build_redist
        
  finish:
    needs:
      - build_ubuntu
      - build_macos
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3 
    
    - name:  Restore cached build 
      uses: actions/cache@v3
      with:
        path: ./*
        key: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }}-${{ github.run_id }} 
        restore-keys: cache-${{ hashFiles('**/*.tar.*', 'lzma/DOC/*.txt' ) }}
        enableCrossOsArchive: true  
    - name: Zip artifact for deployment
      run: zip -r libacfutils.zip ./* 
    - uses: actions/upload-artifact@v3
      with:
        name: libacfutils-full
        path: libacfutils.zip    
